$("#header").load("goods-header.html",function(){
 $(".t1")
      .hover(function(){
      $(".menuW2").toggleClass("in")
  })
  $(".t2")
        .hover(function(){
        $(".menuW1").toggleClass("in1")
    })
  $(".t3")
        .hover(function(){
        $(".menuW3").toggleClass("in1")
    })
  $(".t4")
        .hover(function(){
        $(".menuW4").toggleClass("in1")
   })
  $(".t5")
        .hover(function(){
        $(".menuW5").toggleClass("in1")
   })
  $(".t6")
        .hover(function(){
        $(".menuW6").toggleClass("in1")
   })
  $(".t7")
        .hover(function(){
        $(".menuW7").toggleClass("in1")
   })
  $(".t8")
        .hover(function(){
        $(".menuW8").toggleClass("in1")
   })
  $(".t9")
        .hover(function(){
        $(".menuW9").toggleClass("in1")
   })
  $(".t10")
        .hover(function(){
        $(".menuW10").toggleClass("in1")
   })
   })